---
# Get CPU fact and create slurm.conf
- hosts: workers
  gather_facts: true
  become: yes
  vars:
    master: __MASTERNODE__
  tasks:
    - template: src=slurm_conf.j2 dest=/etc/slurm/slurm.conf
      delegate_to: localhost
    - systemd:
        name: slurmctld
        state: restarted
      delegate_to: localhost

- hosts: workers
  gather_facts: true
  become: yes
  vars:
    master: __MASTERNODE__
  tasks:
    - template: src=slurm_conf.j2 dest=/etc/slurm/slurm.conf
    - systemd:
        name: slurmd
        state: restarted
